### ISSUE TITLE
Extruded beam sections and selection

### ISSUE THREAD

**Issue by johnnyontheweb** [madil4/awatif#355]
First of all, congrats for this interesting project.

I'm wondering if you plan to implement the extruded view in awatif-ui and if it's possible to select nodes or elements in 3d view.

Ps
What is the license of your code?

**Comment by madil4** [comment]
Hey @johnnyontheweb, thanks for your kind words, and yes both features are on the roadmap. If interested in helping us we have a LinkedIn chat group where we communicate. Connect with me here to add you https://www.linkedin.com/in/madil4/

**Comment by johnnyontheweb** [comment]
Thanks for you replies. By now I cannot code in TS or JS, so I can't really give a hand.
I'll continue to follow updates from you, thanks for the link!
