### ISSUE TITLE
For all functions use an object instead of arguments

### ISSUE THREAD

**Issue by madil4** [madil4/awatif#395]
```typescript
// Instead of 
const output = function(input1, input2);

// Use 
const output = function({param1: input1, param2: input2});
```

I argue this approach is:
- More readable, as you can see what the local variables are called inside the function without opening the function or using an IDE.
- More extendable, as changing the inputs won't break the code. Objects can be extended without reordering the arguments.
- Allows you to override inputs using the spread operator: function({...defaults, change: new})

**Comment by madil4** [comment]
@kaison428, @gottn @ENG-Mazri @calmense if you don't object I would like to follow this approach.

**Comment by madil4** [comment]
Well, I thought about it more, for all functions, it is overkill is, it is more for the UI component (function) as they might change a lot to prevent breaking changing and also for functions that take a lot of arguments (more than 3)

**Comment by kaison428** [comment]
This sounds like a good approach to me
